name: hafilaty
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

# =================================================================
# 1. DEPENDENCIES (Packages required for the app to run)
# =================================================================
dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^14.7.10 #forscedsualnotifecation
  flutter_local_notifications: ^17.0.0
  google_maps_flutter: ^2.12.0  # For the interactive map
  geolocator: ^12.0.0          # To get the user's current GPS position
  firebase_auth: ^4.16.0 
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0
  firebase_database: ^10.5.7
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  translator: ^0.1.7
  intl: ^0.20.2
  hijri: ^3.0.0
  http: ^0.13.6
  url_launcher: ^6.3.2
  
  
# =================================================================
# 2. DEV DEPENDENCIES (Packages used for development/tools)
# =================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0

# =================================================================
# 3. ROOT-LEVEL CONFIGURATION (No indentation - Starts at Column 1)
# =================================================================
flutter_native_splash:
  color: "0D1B36"
  image: assets/hafilaty_logo.png

# =================================================================
# 4. FLUTTER SECTION (For assets, fonts, etc.)
# =================================================================
flutter: # <--- ROOT LEVEL (Column 1)

  uses-material-design: true # <--- Indented 2 spaces

  assets: # <--- Indented 2 spaces
    - assets/
    - assets/translations/ # <--- Indented 4 spaces (Ensure your images are here)

  fonts: # <--- Indented 2 spaces
    - family: HafilatyArabic # <--- Indented 4 spaces
      fonts: # <--- Indented 6 spaces
        - asset: fonts/NeoSansArabic.ttf # <--- Indented 8 spaces