// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMPnEWiSdWzAHMqO43hb_GS9Hmb1pPwk',
    appId: '1:290002889120:web:f7854cc718d264020f5cc5',
    messagingSenderId: '290002889120',
    projectId: 'hafilaty-80caf',
    authDomain: 'hafilaty-80caf.firebaseapp.com',
    storageBucket: 'hafilaty-80caf.firebasestorage.app',
    measurementId: 'G-3EN1RJLHCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ8-U9CbP1cA-Axgo9k9t0hUYnRQ8KQHw',
    appId: '1:290002889120:android:5d28ed47ee360b700f5cc5',
    messagingSenderId: '290002889120',
    projectId: 'hafilaty-80caf',
    storageBucket: 'hafilaty-80caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdhg6fdHRMCGRslSpoeT9-AP-0r8sJak',
    appId: '1:290002889120:ios:945adf57fb5c19720f5cc5',
    messagingSenderId: '290002889120',
    projectId: 'hafilaty-80caf',
    storageBucket: 'hafilaty-80caf.firebasestorage.app',
    iosBundleId: 'com.example.hafilaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdhg6fdHRMCGRslSpoeT9-AP-0r8sJak',
    appId: '1:290002889120:ios:945adf57fb5c19720f5cc5',
    messagingSenderId: '290002889120',
    projectId: 'hafilaty-80caf',
    storageBucket: 'hafilaty-80caf.firebasestorage.app',
    iosBundleId: 'com.example.hafilaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWMPnEWiSdWzAHMqO43hb_GS9Hmb1pPwk',
    appId: '1:290002889120:web:bfe30763f896f3020f5cc5',
    messagingSenderId: '290002889120',
    projectId: 'hafilaty-80caf',
    authDomain: 'hafilaty-80caf.firebaseapp.com',
    storageBucket: 'hafilaty-80caf.firebasestorage.app',
    measurementId: 'G-Y0GLJK6BB3',
  );
}
