import 'package:flutter/material.dart';
// 1. Import the core Firebase package
import 'package:firebase_core/firebase_core.dart';
// 2. Import the configuration file generated by the CLI
import 'firebase_options.dart';
// Your screen file
import 'screens/LoginScreen.dart'; 


// 3. Make the main function asynchronous
void main() async {
  // A. Ensures Flutter is ready to call native code (essential for plugins)
  WidgetsFlutterBinding.ensureInitialized(); 

  // B. Initialize Firebase using the platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // C. Run your application only after Firebase is initialized
  runApp(const HafilatyApp());
}

class HafilatyApp extends StatelessWidget {
  const HafilatyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: MaterialApp(
        title: 'Hafilaty',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: 'HafilatyArabic', 
        ),
        home: const LoginScreen(), 
      ),
    );
  }
}